-- Postgres form of `sqlite/0002_search_history.sql` — see that file's header
-- for what the table is, and `migrations/postgres/0001_initial.sql`'s header
-- for the three dialect differences this schema-change file has to reapply:
-- `TEXT` instead of `DATETIME` for `created_at`, `GENERATED BY DEFAULT AS
-- IDENTITY` on the primary key (Postgres has no rowid to autoincrement from),
-- and no bare `BOOLEAN DEFAULT 0` — moot here, since `opened` is already
-- `INTEGER`, not `BOOLEAN`, for the `Any`-driver reason `sqlite/0002_…`
-- documents.
--
-- Do not edit this file once applied: it is checksummed like every other
-- migration. A schema change is a new `000N_*.sql` in *both* directories.
CREATE TABLE IF NOT EXISTS search_history (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	workspace_id INTEGER,
	query VARCHAR NOT NULL,
	engine VARCHAR(32) NOT NULL,
	source VARCHAR(32) NOT NULL,
	opened INTEGER NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_search_history_workspace_id_workspace FOREIGN KEY(workspace_id) REFERENCES workspace (id)
);

CREATE INDEX IF NOT EXISTS ix_search_history_workspace_id_created_at ON search_history (workspace_id, created_at);
