-- Postgres form of `sqlite/0003_media_jobs.sql` — see that file's header for
-- what the table is, and `migrations/postgres/0001_initial.sql`'s header for
-- the dialect differences (IDENTITY primary key, TEXT timestamps).
--
-- Do not edit this file once applied: it is checksummed like every other
-- migration. A schema change is a new `000N_*.sql` in *both* directories.
CREATE TABLE IF NOT EXISTS media_jobs (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	kind VARCHAR(16) NOT NULL,
	prompt TEXT NOT NULL,
	enhanced_prompt TEXT,
	status VARCHAR(16) NOT NULL DEFAULT 'queued',
	error TEXT,
	width INTEGER NOT NULL,
	height INTEGER NOT NULL,
	length INTEGER NOT NULL DEFAULT 0,
	seed BIGINT NOT NULL,
	comfy_prompt_id VARCHAR(64),
	file_name VARCHAR(255),
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_media_jobs_created_at ON media_jobs (created_at);
