-- Postgres form of `sqlite/0009_ad_campaigns.sql` — see that file for what the
-- table is and why the brand brief is its own column.
--
-- Do not edit this file once applied: it is checksummed like every other
-- migration. A schema change is a new `00NN_*.sql` in *both* directories.

ALTER TABLE project ADD COLUMN brand_json TEXT;

CREATE TABLE IF NOT EXISTS ad_campaigns (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	project_id INTEGER NOT NULL REFERENCES project (id),
	team_template_id INTEGER REFERENCES teamtemplate (id),
	platform VARCHAR(32) NOT NULL,
	brief TEXT NOT NULL,
	status VARCHAR(16) NOT NULL DEFAULT 'running',
	error TEXT,
	copy_json TEXT,
	user_id INTEGER REFERENCES users (id),
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_ad_campaigns_project_id ON ad_campaigns (project_id);
CREATE INDEX IF NOT EXISTS ix_ad_campaigns_user_id ON ad_campaigns (user_id);
