/**
 * AUTO-GENERATED by `scripts/sync_contract_enums.py`.
 * Backend source of truth: `app/shared_enums.py`.
 * Do not edit manually.
 */

export const PROCESS_STATUSES = ["pending", "planning", "approval_required", "approved", "task_review_required", "running", "completed", "failed", "cancelled"] as const;
export type ProcessStatus = typeof PROCESS_STATUSES[number];

export const TASK_STATUSES = ["pending", "running", "awaiting_review", "completed", "failed"] as const;
export type TaskStatus = typeof TASK_STATUSES[number];

export const REVIEW_DECISIONS = ["approve", "reject", "request_changes"] as const;
export type ReviewDecision = typeof REVIEW_DECISIONS[number];

export const PROCESS_RETRY_MODES = ["planning", "execution", "task"] as const;
export type ProcessRetryMode = typeof PROCESS_RETRY_MODES[number];

export const PROCESS_SYNC_ACTIONS = ["none", "blocked", "aligned_status", "requeued_plan", "requeued_execution"] as const;
export type ProcessSyncAction = typeof PROCESS_SYNC_ACTIONS[number];
