//! The check that `migrations/postgres/` is a schema Postgres will actually
//! accept, run against a real server.
//!
//! **This is the thing that blocked Postgres, and it is not the query sites.**
//! `migrations/sqlite/0001_initial.sql` uses `DATETIME` 57 times and `DATETIME`
//! is not a Postgres type at all, so the schema could not apply; and every
//! primary key is `id INTEGER NOT NULL` leaning on SQLite's rowid, which
//! Postgres has no equivalent for, so every INSERT that omits an id would fail.
//! Converting `AppState`'s 280 `state.pool` sites before proving those two
//! would have been 280 edits nothing could verify.
//!
//! **Skipped when there is no server to talk to.** CI provides one as a service
//! container; a developer machine may or may not. A skipped run says so rather
//! than passing quietly.
//!
//! **It never touches the tables in the DSN's database** — that is somebody's
//! actual data. It creates a private schema, points `search_path` at it so
//! every unqualified `CREATE TABLE` lands there, and drops it at the end. A
//! separate database would be tidier still, but `CREATEDB` is a privilege a
//! normal application role does not have, and requiring a superuser to run the
//! suite is worse than a schema that is dropped.

use agent_platform_server::db::{self, Backend};
use sqlx::{Executor, Row};

/// Deliberately not a name anything else would choose — this schema gets a
/// `DROP … CASCADE`, so a collision with a real one would be expensive.
const SCRATCH_SCHEMA: &str = "agent_platform_migration_test";

/// `TEST_DATABASE_URL`, else whatever `DATABASE_URL` the repo's `.env` sets —
/// the same loader the server uses, so no DSN has to be repeated anywhere.
fn dsn() -> Option<String> {
    agent_platform_server::dotenv::load_env_files();
    agent_platform_server::env_opt("TEST_DATABASE_URL")
        .or_else(|| agent_platform_server::env_opt("DATABASE_URL"))
        .filter(|url| Backend::from_url(url) == Backend::Postgres)
}

/// The same DSN with every unqualified name resolving inside `schema`.
///
/// `public` stays on the path so the extensions and types that live there are
/// still reachable; it is second, so nothing this test creates can land in it.
fn with_schema(dsn: &str, schema: &str) -> String {
    let sep = if dsn.contains('?') { '&' } else { '?' };
    format!("{dsn}{sep}options=-c%20search_path%3D{schema},public")
}

#[tokio::test]
async fn the_postgres_schema_applies_and_ids_generate() {
    let Some(dsn) = dsn() else {
        eprintln!(
            "skipped: no Postgres DSN (set TEST_DATABASE_URL, or DATABASE_URL in .env)"
        );
        return;
    };

    let admin = sqlx::PgPool::connect(&dsn).await.expect("connect");

    // **Refuse to run if the name is already taken.** The cleanup below is a
    // `DROP … CASCADE`, and the one way it could destroy real data is finding a
    // schema this test did not create.
    let taken: Option<String> = sqlx::query_scalar(
        "SELECT schema_name FROM information_schema.schemata WHERE schema_name = $1",
    )
    .bind(SCRATCH_SCHEMA)
    .fetch_optional(&admin)
    .await
    .expect("look for an existing schema");
    assert!(
        taken.is_none(),
        "schema {SCRATCH_SCHEMA} already exists; refusing to drop a schema this test did not create"
    );

    admin
        .execute(format!("CREATE SCHEMA {SCRATCH_SCHEMA}").as_str())
        .await
        .expect("create the scratch schema");

    let result = exercise(&with_schema(&dsn, SCRATCH_SCHEMA)).await;

    // Dropped whether or not the assertions held, so a failing run does not
    // leave the schema behind for the next one to refuse on.
    let _ = admin.execute(format!("DROP SCHEMA {SCRATCH_SCHEMA} CASCADE").as_str()).await;
    admin.close().await;

    result.expect("the postgres schema");
}

async fn exercise(url: &str) -> Result<(), String> {
    let pool = db::connect_lazy(url, Backend::Postgres);

    // 1. The whole schema applies. This is the assertion `DATETIME` failed.
    db::ensure_schema(&pool).await.map_err(|e| format!("ensure_schema: {e}"))?;
    // And again, because every start after the first runs it against a database
    // that is already at head.
    db::ensure_schema(&pool).await.map_err(|e| format!("second ensure_schema: {e}"))?;

    // 2. An INSERT that omits the id gets one. This is the assertion the rowid
    //    primary key failed — without `GENERATED BY DEFAULT AS IDENTITY` it is
    //    a null-violation on every create the server does.
    let row = sqlx::query(
        "INSERT INTO project (name, created_at, updated_at) \
         VALUES ('generated', NOW(), NOW()) RETURNING id",
    )
    .fetch_one(&pool)
    .await
    .map_err(|e| format!("insert without an id: {e}"))?;
    let generated: i32 = row.try_get("id").map_err(|e| format!("read the id back: {e}"))?;
    assert!(generated > 0, "identity produced {generated}");

    // 3. An explicit id still works — `BY DEFAULT`, not `ALWAYS`. Seeds and
    //    this repo's own tests insert ids.
    sqlx::query(
        "INSERT INTO project (id, name, created_at, updated_at) \
         VALUES (4242, 'explicit', NOW(), NOW())",
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("insert with an explicit id: {e}"))?;

    // 4. `db::sql` rewrites `?` to `$n` for real, against a real parser. Every
    //    converted query site depends on this and SQLite can never exercise it.
    let query = db::sql("SELECT name FROM project WHERE id = ? AND name = ?", Backend::Postgres);
    let found: String = sqlx::query_scalar(&query)
        .bind(4242_i64)
        .bind("explicit")
        .fetch_one(&pool)
        .await
        .map_err(|e| format!("placeholder rewriting: {e}"))?;
    assert_eq!(found, "explicit");

    // 5. The casts `db.rs` documents decode under the `Any` driver, which is
    //    the whole reason they are written that way. A bare timestamp column
    //    does not, on either backend.
    let row = sqlx::query(
        &db::sql(
            "SELECT CAST(id AS BIGINT) AS id, CAST(created_at AS TEXT) AS created_at \
             FROM project WHERE id = ?",
            Backend::Postgres,
        ),
    )
    .bind(4242_i64)
    .fetch_one(&pool)
    .await
    .map_err(|e| format!("the documented casts: {e}"))?;
    let id: i64 = row.try_get("id").map_err(|e| format!("decode CAST(id AS BIGINT): {e}"))?;
    let created: String =
        row.try_get("created_at").map_err(|e| format!("decode CAST(created_at AS TEXT): {e}"))?;
    assert_eq!(id, 4242);
    assert!(!created.is_empty());

    // 6. The queries of the domains that have been converted off `state.pool`,
    //    run as the handlers send them. SQLite accepts all of these and proves
    //    nothing about them: the `?` rewriting, the `CAST`s and — the one that
    //    actually bit — `enabled = TRUE` against a BOOLEAN column, where
    //    `enabled = 1` is a type error here and fine there.
    //
    //    ponytail: the SQL, not the handler. Driving `auth::resolve` end to end
    //    would need an `AppState` built from a URL rather than a file path;
    //    worth doing once enough domains are converted that the SQL alone stops
    //    being the whole risk.
    //    The bind types are spelled per query rather than shared, because
    //    Postgres checks them and SQLite does not: passing a string where an
    //    `integer` column is compared is `operator does not exist: integer =
    //    text` here and a silent no-match there.
    let text_bound = [
        (
            "auth::resolve_workspace_token",
            "SELECT CAST(id AS BIGINT) AS id, CAST(workspace_id AS BIGINT) AS workspace_id, \
                    prefix, scopes_json, status, held_reason, \
                    CAST(rate_limit_per_minute AS BIGINT) AS rate_limit_per_minute, \
                    CAST(expires_at AS TEXT) AS expires_at, \
                    CAST(last_used_at AS TEXT) AS last_used_at \
             FROM api_tokens WHERE token_hash = ?",
        ),
        (
            "workflow_engine::run_due_workflows",
            "SELECT CAST(id AS BIGINT) AS id, steps_json, \
                    CAST(interval_seconds AS BIGINT) AS interval_seconds FROM workflows \
             WHERE enabled = TRUE AND interval_seconds IS NOT NULL \
               AND next_run_at IS NOT NULL AND CAST(next_run_at AS TEXT) <= ?",
        ),
    ];
    for (label, query) in text_bound {
        sqlx::query(&db::sql(query, Backend::Postgres))
            .bind("2026-01-01 00:00:00.000000")
            .fetch_optional(&pool)
            .await
            .map_err(|e| format!("{label}: {e}"))?;
    }

    // The two column lists are `pub` so this runs the *real* strings rather than
    // a copy that drifts. They are the ones carrying a `BOOLEAN` column through
    // the `Any` driver, which is the decode SQLite cannot exercise: it stores
    // booleans as integers and is happy either way.
    for (label, query) in [
        (
            "workflows::WORKFLOW_COLUMNS",
            format!(
                "SELECT {} FROM workflows WHERE id = ?",
                agent_platform_server::workflows::WORKFLOW_COLUMNS
            ),
        ),
        (
            "workflows::RUN_COLUMNS",
            format!(
                "SELECT {} FROM workflow_runs WHERE id = ?",
                agent_platform_server::workflows::RUN_COLUMNS
            ),
        ),
        (
            "api_tokens::TOKEN_COLUMNS",
            format!(
                "SELECT {} FROM api_tokens WHERE id = ?",
                agent_platform_server::api_tokens::TOKEN_COLUMNS
            ),
        ),
        (
            "coder::THREAD_COLUMNS",
            format!(
                "SELECT {} FROM coder_chat_threads WHERE id = ?",
                agent_platform_server::coder::THREAD_COLUMNS
            ),
        ),
        (
            "teams::TEAM_COLUMNS",
            format!(
                "SELECT {} FROM teamtemplate WHERE id = ?",
                agent_platform_server::teams::TEAM_COLUMNS
            ),
        ),
        (
            "workspaces::COLUMNS",
            format!(
                "SELECT {} FROM workspace WHERE id = ?",
                agent_platform_server::workspaces::COLUMNS
            ),
        ),
        (
            "assistant::CHAT_THREAD_COLUMNS",
            format!(
                "SELECT {} FROM assistant_chat_threads WHERE id = ?",
                agent_platform_server::assistant::CHAT_THREAD_COLUMNS
            ),
        ),
        (
            "processes::PROCESS_COLUMNS",
            format!(
                "SELECT {} FROM process WHERE id = ?",
                agent_platform_server::processes::PROCESS_COLUMNS
            ),
        ),
        (
            "processes::TASK_COLUMNS",
            format!(
                "SELECT {} FROM tasknode WHERE id = ?",
                agent_platform_server::processes::TASK_COLUMNS
            ),
        ),
        (
            "processes::EVENT_COLUMNS",
            format!(
                "SELECT {} FROM eventlog WHERE id = ?",
                agent_platform_server::processes::EVENT_COLUMNS
            ),
        ),
    ] {
        sqlx::query(&db::sql(&query, Backend::Postgres))
            .bind(4242_i64)
            .fetch_optional(&pool)
            .await
            .map_err(|e| format!("{label}: {e}"))?;
    }

    let id_bound = [
        (
            "auth::archived workspace",
            "SELECT CAST(archived_at AS TEXT) FROM workspace WHERE id = ?",
        ),
        (
            "workspace_files::require_project",
            "SELECT CAST(id AS BIGINT) FROM project WHERE id = ?",
        ),
        (
            "workspace_files::require_process_for_project",
            "SELECT CAST(project_id AS BIGINT) FROM process WHERE id = ?",
        ),
    ];
    for (label, query) in id_bound {
        sqlx::query(&db::sql(query, Backend::Postgres))
            .bind(4242_i64)
            .fetch_optional(&pool)
            .await
            .map_err(|e| format!("{label}: {e}"))?;
    }

    pool.close().await;
    Ok(())
}

#[test]
fn the_search_path_is_appended_to_whatever_the_dsn_already_carries() {
    assert_eq!(
        with_schema("postgresql://u:p@localhost/agent_platform", "scratch"),
        "postgresql://u:p@localhost/agent_platform?options=-c%20search_path%3Dscratch,public"
    );
    assert_eq!(
        with_schema("postgresql://u:p@localhost/agent_platform?sslmode=require", "scratch"),
        "postgresql://u:p@localhost/agent_platform?sslmode=require&options=-c%20search_path%3Dscratch,public"
    );
}
