"""Generate the desktop client's Rust enums from backend canonical enums."""

from __future__ import annotations

from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from app.shared_enums import (
    ProcessRetryMode,
    ProcessStatus,
    ProcessSyncAction,
    ReviewDecision,
    TaskStatus,
    enum_values,
)


_RUST_ENUMS = (
    ("ProcessStatus", "PROCESS_STATUSES", ProcessStatus),
    ("TaskStatus", "TASK_STATUSES", TaskStatus),
    ("ReviewDecision", "REVIEW_DECISIONS", ReviewDecision),
    ("ProcessRetryMode", "PROCESS_RETRY_MODES", ProcessRetryMode),
    ("ProcessSyncAction", "PROCESS_SYNC_ACTIONS", ProcessSyncAction),
)


def _to_rust_enum(type_name: str, const_name: str, values: tuple[str, ...]) -> str:
    variants = [(v, "".join(p.title() for p in v.split("_"))) for v in values]
    lines = [
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]",
        f"pub enum {type_name} {{",
    ]
    for value, variant in variants:
        lines.append(f'    #[serde(rename = "{value}")]')
        lines.append(f"    {variant},")
    # Server may grow values before the client is rebuilt; never fail to parse.
    lines.append("    #[serde(other)]")
    lines.append("    Unknown,")
    lines.append("}")
    lines.append("")
    lines.append(f"impl {type_name} {{")
    lines.append("    pub fn as_str(&self) -> &'static str {")
    lines.append("        match self {")
    for value, variant in variants:
        lines.append(f'            Self::{variant} => "{value}",')
    lines.append('            Self::Unknown => "unknown",')
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    items = ", ".join(f"{type_name}::{variant}" for _, variant in variants)
    lines.append(
        f"pub const {const_name}: [{type_name}; {len(variants)}] = [{items}];"
    )
    return "\n".join(lines) + "\n"


def build_rust() -> str:
    header = (
        "//! AUTO-GENERATED by `scripts/sync_contract_enums.py`.\n"
        "//! Backend source of truth: `app/shared_enums.py`.\n"
        "//! Do not edit manually.\n\n"
    )
    return header + "\n".join(
        _to_rust_enum(type_name, const_name, enum_values(enum))
        for type_name, const_name, enum in _RUST_ENUMS
    )


def main() -> None:
    rust_path = REPO_ROOT / "desktop" / "crates" / "client" / "src" / "enums_gen.rs"
    rust_path.parent.mkdir(parents=True, exist_ok=True)
    rust_path.write_text(build_rust(), encoding="utf-8")
    print(f"Updated {rust_path}")


if __name__ == "__main__":
    main()

