"""Generate frontend enum/types from backend canonical enums."""

from __future__ import annotations

from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from app.shared_enums import (
    ProcessRetryMode,
    ProcessStatus,
    ProcessSyncAction,
    ReviewDecision,
    TaskStatus,
    enum_values,
)


def _to_ts_const(name: str, type_name: str, values: tuple[str, ...]) -> str:
    items = ", ".join(f'"{value}"' for value in values)
    return (
        f"export const {name} = [{items}] as const;\n"
        f"export type {type_name} = typeof {name}[number];\n"
    )


def build_typescript() -> str:
    return """/**
 * AUTO-GENERATED by `scripts/sync_contract_enums.py`.
 * Backend source of truth: `app/shared_enums.py`.
 * Do not edit manually.
 */

""" + (
        _to_ts_const("PROCESS_STATUSES", "ProcessStatus", enum_values(ProcessStatus))
        + "\n"
        + _to_ts_const("TASK_STATUSES", "TaskStatus", enum_values(TaskStatus))
        + "\n"
        + _to_ts_const("REVIEW_DECISIONS", "ReviewDecision", enum_values(ReviewDecision))
        + "\n"
        + _to_ts_const("PROCESS_RETRY_MODES", "ProcessRetryMode", enum_values(ProcessRetryMode))
        + "\n"
        + _to_ts_const("PROCESS_SYNC_ACTIONS", "ProcessSyncAction", enum_values(ProcessSyncAction))
    )


def main() -> None:
    flow_ui_path = REPO_ROOT.parent / "flow-ui" / "src" / "api" / "enums.ts"
    output_path = flow_ui_path if flow_ui_path.parent.exists() else REPO_ROOT / "web" / "src" / "api" / "enums.ts"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_typescript(), encoding="utf-8")
    print(f"Updated {output_path}")


if __name__ == "__main__":
    main()

