import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useCoreStore } from '../integration/store/coreStore'
import { useActiveTeam } from '../integration/store/teamStore'
import { Button } from '@/components/ui/button'
import { TeamOutputBadge } from './components/TeamOutputBadge'
import { ModalBackdrop, ModalRoot } from './components/ModalChrome'
import { FinalOutputBody } from './projectOutput/FinalOutputBody'
import { FinalOutputFooter } from './projectOutput/FinalOutputFooter'

export function FinalOutputModal() {
  const {
    isFinalOutputOpen,
    setFinalOutputOpen,
    finalOutput,
    finalAssetType,
    finalAssetContent,
    isGeneratingAsset,
    referenceImages,
  } = useCoreStore()
  const activeTeam = useActiveTeam()
  const [copied, setCopied] = useState(false)

  if (!isFinalOutputOpen) return null

  const handleCopy = async () => {
    await navigator.clipboard.writeText(finalOutput || '')
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <ModalRoot paddingClassName="p-4">
      <ModalBackdrop tone="lightXl" onRequestClose={() => setFinalOutputOpen(false)} />
      <div
        className="relative flex max-h-[90vh] w-180 max-w-full flex-col overflow-hidden rounded-[32px] border border-black/10 bg-zinc-50 shadow-2xl"
        onMouseDown={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-black/5 bg-white px-8 py-6">
          <div className="flex items-center gap-6">
            <div>
              <h2 className="flex items-center gap-2 text-sm font-black uppercase tracking-widest text-darkDelegation">
                {finalAssetType !== 'text' && (
                  <span className="rounded-md bg-darkDelegation px-2 py-0.5 text-[8px] tracking-tighter text-white">
                    {(activeTeam?.outputType || finalAssetType).toUpperCase()}
                  </span>
                )}
                Final {finalAssetType} Deliverable
              </h2>
              <p className="mt-0.5 text-[11px] text-zinc-400">Refined and generated by your autonomous team</p>
            </div>
            <TeamOutputBadge system={activeTeam} className="hidden sm:flex" />
            <Button type="button" variant="outline" size="sm" className="text-[9px] font-black uppercase tracking-widest" asChild>
              <Link to="/project-output" onClick={() => setFinalOutputOpen(false)}>
                Open full page
              </Link>
            </Button>
          </div>
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            onClick={() => setFinalOutputOpen(false)}
            className="size-8 rounded-full text-lg leading-none text-zinc-400 hover:bg-zinc-100 hover:text-zinc-700"
            aria-label="Close"
          >
            ✕
          </Button>
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto px-8 py-8">
          <div className="markdown-content font-sans text-sm leading-relaxed text-zinc-700">
            <FinalOutputBody
              finalOutput={finalOutput || ''}
              finalAssetType={finalAssetType}
              finalAssetContent={finalAssetContent ?? ''}
              isGeneratingAsset={isGeneratingAsset}
            />
          </div>
        </div>

        <FinalOutputFooter
          referenceImages={referenceImages}
          finalAssetType={finalAssetType}
          copied={copied}
          onCopy={handleCopy}
        />
      </div>
    </ModalRoot>
  )
}
